### ISSUE TITLE
undefined & Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code

### ISSUE THREAD

**Issue by Ro706** [Ro706/avabodh#1]
![image](https://github.com/user-attachments/assets/321b2680-4b38-472d-bf3b-090d9d483142)

**Comment by Ro706** [comment]
"undefined" is not valid JSON
SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at HTMLDivElement.<anonymous> (http://localhost:3000/assets/js/careox.js:490:56)
    at Function.each (http://localhost:3000/assets/jquery/jquery.min.js:2:2976)
    at S.fn.init.each (http://localhost:3000/assets/jquery/jquery.min.js:2:1454)
    at thmOwlInit (http://localhost:3000/assets/js/careox.js:486:25)
    at http://localhost:3000/assets/js/careox.js:714:5
    at dispatch (http://localhost:3000/assets/jquery/jquery.min.js:2:43090)
    at v.handle (http://localhost:3000/assets/jquery/jquery.min.js:2:41074)


![Screenshot 2024-10-07 112209](https://github.com/user-attachments/assets/e1381e49-dd05-4650-867b-5e0885cce30a)
